### PR TITLE
Update Pages.ps1

### PR DESCRIPTION
**Pull request by Szeraax**
Exclude ProgressAction from module pages

### CODE REVIEW

**Comment by Szeraax** [comment]
Also of note is that there is [System.Management.Automation.PSCmdlet]::OptionalCommonParameters that is also a hashset that you don't currently account for. Do you want to exclude those as well?

**Comment by Badgerati** [comment]
Yes, excluding `[System.Management.Automation.PSCmdlet]::OptionalCommonParameters` as well makes sense :)

**Comment by Badgerati** [comment]
Accctually, having `WhatIf` could be useful, it might be an idea to leave it out as it is today but have a switch parameter to let the user toggle if they want to exclude them.

**Comment by CastlegateHOA** [comment]
@Badgerati  I agree with everything you stated. Lets ship this PR as is so that Pwsh 7.4 can use pode.web again. and I'll go file an issue to deal with Optional Common Parameters, kk? That's where we can work out switch vs an array of common params to add back in, etc.

**Comment by Szeraax** [comment]
I agree with everything you stated. Lets ship this PR as is so that Pwsh 7.4 can use pode.web again. and I'll go file an issue to deal with Optional Common Parameters, kk? That's where we can work out switch vs an array of common params to add back in, etc.

**Comment by Szeraax** [comment]
WORKAROUND FOUND!! I no longer need v0.8.4+ to continue work on PowerShellAIAssistant! This PR should still be merged though. 

Wow, I'm so stupid! And happy :D I should have checked to see if the the ConvertTo-PodeWebPage function actually interacts with module scoped data or if its just a wrapper around big hashtables. 

I can just copy this function definition and edit the line to what I want and it works perfectly. 

As for the optional common parameters, I'll go file that issue now so that we keep track of it.

**Pull request merged**
