### PR TITLE
Added Update-PodeWebTextbox ReadOnly parameter

### PR DESCRIPTION
**Pull request by RobinBeismann**
### Description of the Change
Initial take on adding the Readonly parameter.

### Related Issue
The issue for discussion is #411

### CODE REVIEW

**Comment by Badgerati** [comment]
Hi @RobinBeismann,

Well TIL! I did not know you could do that with boolean parameters and `$PSBoundParameters` 😮 

The way I've done this on other output functions is to use `ValidateSet`, and have the default value as `Unchanged` - you can see this on `Update-PodeWebButton` with the likes of `$ColourState`, or `Update-PodeWebCheckbox` with `$State`:
```powershell
[Parameter()]
[ValidateSet('Unchanged', 'Outline', 'Solid')]
[string]
$ColourState = 'Unchanged'

# or

[Parameter()]
[ValidateSet('Unchanged', 'Disabled', 'Enabled')]
[string]
$State = 'Unchanged'
```

What do you think?

So if we want to keep this inline with other functions; possibly something like `$ReadOnlyState`:
```powershell
[Parameter()]
[ValidateSet('Unchanged', 'Disabled', 'Enabled')]
[string]
$ReadOnlyState = 'Unchanged'
```

**Comment by RobinBeismann** [comment]
Ah! I didn't see the `Update-PodeWebButton` example when I was searching for references 😋 I'll update my PR so it aligns with the existing functions.

**Comment by RobinBeismann** [comment]
@Badgerati - Sanity check: `ReadOnlyState` = `Enabled` means the TextBox is being set to readonly, right? 😄

**Comment by RobinBeismann** [comment]
Hey @Badgerati,

I just stumbled upon another thing that made me rethink this: When using `Set-PodeWebSelect` it resets the disabled state of the Select Element also. Is this a bug I should fix in `Set-PodeWebSelect` by checking the current state of the select or should we make the other parameters of `Update-PodeWebSelect` optional and allow that Cmdlet to be used for updating the content solely without modifying any other properties? I could imagine a `ReadOnlyState` flag would make sense there also.

**Comment by RobinBeismann** [comment]
Hey @Badgerati,

sorry to poke, did you see my latest reply? Somewhat want to get this implemented. 😄

**Comment by Badgerati** [comment]
Hey @RobinBeismann,

I have seen it yes; just been hectic at work with a migration so haven't had chance to read properly, sorry.

That is strange that `Set-PodeWebSelect` resets the disabled state, looking at the javascript it runs I wouldn't have thought it would do that 🤔 if it is, then yes it's a bug. Making the parameters on `Update-PodeWebSelect` optional and adding a `-ReadOnlyState` here would be useful as well 😄 it'll likely make sense on most of the Update functions, haha!

And yeah, `ReadOnlyState=Enabled` would be that the textbox is set to readonly 😄

**Comment by RobinBeismann** [comment]
> Hey @RobinBeismann,
> 
> I have seen it yes; just been hectic at work with a migration so haven't had chance to read properly, sorry.
> 
> That is strange that `Set-PodeWebSelect` resets the disabled state, looking at the javascript it runs I wouldn't have thought it would do that 🤔 if it is, then yes it's a bug. Making the parameters on `Update-PodeWebSelect` optional and adding a `-ReadOnlyState` here would be useful as well 😄 it'll likely make sense on most of the Update functions, haha!
> 
> And yeah, `ReadOnlyState=Enabled` would be that the textbox is set to readonly 😄 

No worries and thanks, I'll implement that. Probably not for all functions at once but at least for those. I'll also have a check on why `Set-PodeSelect` resets the disabled state.

**Comment by RobinBeismann** [comment]
Ready for review. 😄 
We now have:
- `-ReadOnly` on `New-PodeWebSelect`
- `-ReadOnlyState` on `Update-PodeWebSelect`
- `-ReadOnlyState` on `Update-PodeWebTextbox`

So `Set-PodeWebSelect` didn't even reset the disabled state, I just messed up and never set it, as it didn't exist as parameter.

**Comment by Badgerati** [comment]
The changes look good to me, I'll try an test them this week :)

**Comment by RobinBeismann** [comment]
Hi @Badgerati,

I didn't check your commits in #439 in detail, however given that you move the rendering out of Pode and into JS, this would break this commit right? I was looking to add more features into it (for DatePicker Objects) but I'd wait if #439 changes the way it works.

**Comment by Badgerati** [comment]
Hi @RobinBeismann,

Yes, you're correct, the changes in #439 do break this commit. I'll merge this PR as is so the changes come along in the initial migration 😃

**Comment by RobinBeismann** [comment]
> Hi @RobinBeismann,
> 
> Yes, you're correct, the changes in #439 do break this commit. I'll merge this PR as is so the changes come along in the initial migration 😃 
> 
> 

Ah damn, thought I was going to add more elements and switches next week as I'll need them for an upcoming project. 😅
Any idea when you aim for the migration?

**Comment by Badgerati** [comment]
I'm about 60% of the way through at the moment, so hopefully within the next week.

I will need to write up a quick migration guide for it, as the work obsoletes the `Out-` functions in place of their main `New-` functions - which also means a v1.0 release!

What elements were you looking at adding? 😮

**Comment by RobinBeismann** [comment]
> I'm about 60% of the way through at the moment, so hopefully within the next week.
> 
> I will need to write up a quick migration guide for it, as the work obsoletes the `Out-` functions in place of their main `New-` functions - which also means a v1.0 release!

Ah cool! 

> What elements were you looking at adding? 

Meant enhancements, sorry. Mainly for DateTime but I'll probably stumble upon more. 😅

**Comment by Badgerati** [comment]
Hey,

I'm in the last stages of the migration for #439 - just Navigation elements, redirect actions, and theme updates to go 😃 all of the other elements are done. It's definitely a v1.0 release for sure, so will also need to write a migration guide - and do some thorough testing.

Feel free to have a gander, I can't see the logic changing much now 🤞 the only part I can see is splitting the elements in different files, and running a bundle + minify tool during build/pack for releasing.

(you'll also spot a lot of "TODO" notes 😂 these will all be ticketed up soon)

**Comment by RobinBeismann** [comment]
Hey @Badgerati,

sounds good! I'll have a look next week, here in Germany we have public holidays tomorrow and monday and the enhancements I'm looking for are mainly for a work project. 😄 
Glad to see this project reaching it's first major through!

**Pull request merged**
