### PR TITLE
Update Image.md

### PR DESCRIPTION
**Pull request by Szeraax**
Consider if placing this link to public content should be added to other elements or even on one of the basic tutorials.

### Description of the Change
A clear and concise description of what has been changed.

### Related Issue
A link/reference to the GitHub issue.

### Examples
If relevant, include any examples of using what you have changed.

### Additional Context
Add any other context or screenshots about the pull request request here.

### CODE REVIEW

**Comment by Badgerati** [comment]
It is probably best to have a reference to it on element affected, so it can be clear within parameter of which functions are affected.

Other than Images, also affected are:
* Video: the `-Thumbnail` parameter, and the `-Url` parameters on VideoSource and MediaSource
* Audio: The `-Url` parameters on AudioSource and MediaSource
* CommentBlock: The `-Icon` parameter

**Comment by Szeraax** [comment]
Happy to do so, @Badgerati. Hows that look?

**Comment by Badgerati** [comment]
Hey @Szeraax, all LGTM! Happy to merge if you are

**Comment by Szeraax** [comment]
Good to merge.

**Pull request merged**
